Update Shell-Script
Fixing Bug

diff --git a/Shell-Script b/Shell-Script
--- a/Shell-Script
+++ b/Shell-Script
@@ -1,13 +1,89 @@
-#!/bin/bash
+#!/bin/sh
+set -e
+#
+# This script is meant for quick & easy install via:
+#   'curl -sSL https://<url>.domain.com/ | sh'
+# or:
+#   'wget -qO- https://<url>.domain.com/ | sh'
+#
 
-apt-get update
-apt-get install npm
-apt-get install nodejs
-apt-get install git
-npm install bower -g
-ln -s /usr/bin/nodejs /usr/bin/node
-apt-get install libapache2-mod-python libapache2-mod-python-doc apache2
-cd /var/www/html/
-git clone git://github.com/densitydesign/raw.git
-cd raw/
-bower install
+url=''
+
+
+command_exists() {
+	command -v "$@" > /dev/null 2>&1
+}
+
+case "$(uname -m)" in
+	*64)
+		;;
+	*)
+		echo >&2 'Error: you are not using a 64bit platform.'
+		exit 1
+		;;
+esac
+
+
+user="$(id -un 2>/dev/null || true)"
+
+sh_c='sh -c'
+if [ "$user" != 'root' ]; then
+        if command_exists sudo; then
+                sh_c='sudo -E sh -c'
+        elif command_exists su; then
+                sh_c='su -c'
+        else
+                echo >&2 'Error: this installer needs the ability to run commands as root.'
+                echo >&2 'We are unable to find either "sudo" or "su" available to make this happen.'
+                exit 1
+        fi
+fi
+
+curl=''
+if command_exists curl; then
+        curl='curl -sSL'
+elif command_exists wget; then
+        curl='wget -qO-'
+fi
+
+
+# perform some very rudimentary platform detection
+lsb_dist=''
+if command_exists lsb_release; then
+	lsb_dist="$(lsb_release -si)"
+fi
+if [ -z "$lsb_dist" ] && [ -r /etc/lsb-release ]; then
+	lsb_dist="$(. /etc/lsb-release && echo "$DISTRIB_ID")"
+fi
+if [ -z "$lsb_dist" ] && [ -r /etc/os-release ]; then
+	lsb_dist='EC2'
+fi
+if [ -z "$lsb_dist" ] && [ -r /etc/redhat-release ]; then
+	lsb_dist='Redhat'
+fi
+if [ -z "$lsb_dist" ] && [ -r /etc/debian_version ]; then
+	lsb_dist='Debian'
+fi
+case "$lsb_dist" in
+	Debian)
+		(
+			set -x
+			$sh_c 'sleep 3; apt-get update'
+			$sh_c 'sleep 3; apt-get install npm nodejs git libapache2-mod-python libapache2-mod-python-doc apache2'
+			$sh_c 'npm install bower -g'
+			$sh_c 'sleep 3; ln -s /usr/bin/nodej'
+			$sh_c 'cd /var/www/html/; git clone git://github.com/densitydesign/raw.git; cd raw; bower install'
+		)
+		exit 0
+		;;
+
+
+esac
+
+cat >&2 <<'EOF'
+
+  Either your platform is not easily detectable, is not supported by this
+  installer script. 
+
+EOF
+exit 1
